name: Build and deploy Node.js app to Azure Web App - hal-nh-web-iw14a02

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      # スタンドアロンビルドに必要なファイル（.next/standalone）だけをデプロイ用にまとめる
      - name: Copy static files to standalone
        run: |
          cp -R public .next/standalone/public
          cp -R .next/static .next/standalone/.next/static

      # デプロイ対象を.next/standalone配下のファイルに絞ってアップロード
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .next/standalone

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_83C308FCC7924250B14A9B4DF1FBEF72 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AF8EC5E60A154CADA957EF38142E6749 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_34C388CBB3FF4409B8764693F88DF40F }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'hal-nh-web-iw14a02'
          slot-name: 'Production'
          package: .
